kind: EventList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-events-panel-eventlist
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    events: []
    sseEndpoint: "/notifications?composition_id={{ .Values.global.compositionId }}"
    sseTopic: "krateo"
  widgetDataTemplate:
    - forPath: events
      expression: "${ .list }"
  apiRef:
    name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-events
    namespace: {{ .Values.global.compositionNamespace }}