apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-events
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  api:
  - name: getEvents
    path: "/events?composition_id={{ .Values.global.compositionId }}&limit=200"
    verb: GET
    endpointRef:
      name: events-presenter-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: getEventsError
    exportJwt: true
  filter: >
    {
      list: (.getEvents.resources // [])
    }